# nginx proxy address - http://172.17.0.1:3004

name: tldraw
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  tldraw:
    image: foxxmd/tldraw:latest
    pull_policy: always
    container_name: tldraw-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - tldraw
    ports:
      - "172.17.0.1:3004:5858"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/data/tldraw:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5858"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tldraw:
    name: tldraw
    external: false
